### ISSUE TITLE
Easy DSi-exclusive CMake toolchain (regression)

### ISSUE THREAD

**Issue by ds-sloth** [devkitPro/calico#2]
### Congratulations on the Calico release!

A lot of work has clearly gone into it and I am really looking forward to porting all of my various projects. I'm especially excited for WPA support on DSi.

#### Overview:
- Please make it easier to create port applications using the CMake build system in DSi-exclusive mode. This was previously possible by specifying `-specs=dsi_arm9.specs` in libnds.

#### Nature of Request:  
- Addition
  - Please add a `dsi9.specs` file to Calico!
  - Or, a CMake toolchain file for DSi-exclusive homebrew would also be great.

### Why would this feature be useful?

I sometimes build larger cross-platform CMake projects (eg, command-line utilities) for DSi. The codesize plus static memory of these projects frequently exceeds 4MB. In legacy libnds, I would use `-specs=dsi_arm9.specs` to easily and directly build such a codebase in DSi-exclusive mode. In general it's very helpful for the community if it is as easy as possible to port simple applications like this.

**Comment by fincs** [comment]
I think there may have been some confusion here. The legal loadable areas for the 9/7/9i/7i binaries [are as follows](https://problemkaputt.de/gbatek-dsi-cartridge-header.htm), regardless of whether it's a "hybrid" DS/DSi binary or an "exclusive" DSi binary:
```
  ARM9  2004000h..227FFFFh (siz=27C000h) (for NDS mode: 2000000h and up)
  ARM7  2380000h..23BFFFFh (siz=40000h)
  ARM9i 2400000h..267FFFFh (siz=280000h)
  ARM7i 2E80000h..2F87FFFh (siz=108000h)
```

Note that DSi exclusive binaries must still be able to load on DS, because older loaders (including the original DS firmware) have no notion of DSi exclusivity, and they will happily attempt to boot those applications. For this reason DSi exclusive applications are expected to still restrict the size of their 9/7 binaries so that loading them on DS doesn't crash; and when the app is booted they need to display an error message. Note that hbmenu, unlike DS/DSi firmware, does not check binary sizes or the unitcode value in the header; and as such it is still necessary to ensure that binaries don't crash on DS. While it is true that at some point in the past we did provide a linkscript that allowed the static ARM9 binary to overshoot the legal loadable area, we now believe this was a misguided addition, and no longer recommend its use.

Embedding large amounts of code/data statically is generally a bad practice, and it would be a better idea to use NitroFS and/or overlays to dynamically load the code/data at runtime. You can also use DSi exclusive sections by using `.twl.c`/`.twl.cpp`/etc file extensions (recommended), or by explicitly tagging functions or globals with `TWL_CODE`, `TWL_DATA` or `TWL_BSS`.

**Comment by ds-sloth** [comment]
Thanks a lot for the reply! Let me be a bit more specific because I realize that my last message sounded somewhat hypothetical.

I'll tell you a bit about my specific use case, and also outline a possible calico-side solution. Any application-side solutions you can think of would be very welcome.

## My application

This is actually in reference to a major (but currently unreleased) project that has been in active development for years. I'd really appreciate your help getting it to build on libnds 2.0 (or, getting libnds 2.0 to build it).

Concretely, I have a large, multi-platform application, which has a DSi build (as well as many other targets). Less than 1% of its code is DSi-specific. The project also uses multiple upstream libraries built as submodules.

As of its last successful build with libnds 1.x, had 2,918,576 bytes of text and 4,241,568 bytes of BSS.

I now understand that the code size is ~400kb larger than legal, but that is totally new information to me. The code size is likely to both grow and shrink as features are added and optimized.

I can't rename files or add annotations to (most) symbols in source because this is not a DSi-specific codebase.

I'm not familiar with overlays, but I also *think* that they are not a solution. All the symbols need to look statically linked from the perspective of my code, and none of the code is cold enough that I'm willing to pay for position independent code.

I would be perfectly happy for it to simply hang when a DS attempts to load it, but an error message would of course be preferable.

## Possible solution (calico-side fix)

* Add the ability to build an application whose ARM9 binary is a stub included with dkP (eg, print "this application is DSi-exclusive"), and whose ARM9i binary is allowed to exceed the legal 2.5MB limit.
* Make this totally non-default and scary by giving it a name like `dsi9-unsafe.specs`.

I think that from a technical perspective this would solve my issues while also not encouraging a bad practice.

**Comment by ds-sloth** [comment]
(As a temporary experiment, I arbitrarily added `TWL_BSS` and `TWL_CODE` before arbitrary large functions and arrays. This results in successful compilation, but a data abort at a null address on the first TWL_BSS access. This occurs when the application is launched on either hbmenu or unlaunch. Is it the case that `TWL_BSS` only gets mapped for code in `TWL_CODE`? That's a total showstopper for any strategy that uses both the ARM9 and ARM9i regions to store code.)

(As a further experiment, I removed all instances of `TWL_BSS` and manually removed the BSS size check from `ds9.ld`. This resulted in the program crashing on the first call of a `TWL_CODE` function. I guess that I'm not loading these right right.)

**Comment by Lorenzooone** [comment]
@ds-sloth the issue is actually the opposite, it's official menu loading for DSi. It restricts ARM9 size to 2.5MBs. Your code wouldn't crash on a DS, which still has the 4MBs limit. To be clear, regular homebrew loading works perfectly fine on DSi regardless of that 2.5 MBs limitation.

What you could do is make a small binary which then actually does the loading of your bigger binary. If you implement it like that, your limitations would be of 16 MBs on DSi (32 MBs on Debugger DSis, though with some pain) and 4 MBs on DS (8 MBs on Debugger DSs).
And you basically wouldn't need to change your main code routines.

I would have expected it to be kind of a standard way to do this, since there is so much unused space, but I guess big code homebrews are rare, so you have to do the legwork and implement it.

**Comment by ds-sloth** [comment]
> small binary which then actually does the loading of your bigger binary

Thanks for the suggestion! That sounds really promising but I'm scared it will result in PIC. This is a very performance sensitive project and I would prefer to avoid paying for PIC at all costs.

Do you know whether this strategy would result in PIC? And how could I implement it?

**Comment by Lorenzooone** [comment]
> > small binary which then actually does the loading of your bigger binary
> 
> Thanks for the suggestion! That sounds really promising but I'm scared it will result in PIC. This is a very performance sensitive project and I would prefer to avoid paying for PIC at all costs.
> 
> Do you know whether this strategy would result in PIC? And how could I implement it?

I do not know what PIC means in this context... But if you're afraid of the loading costs, they shouldn't be too high, considering they would just become the same costs as your standard project + the extra small stage 1 loading binary.

**Comment by ds-sloth** [comment]
Sorry, PIC is position independent code. When you have normal code, the address of statically allocated variables is known at compile time. This is important because it means that the program can hardcode the address of a member of a specific struct in a static array, thus allowing a lot of intermediate computations to happen at compile time.

What strategies would you normally use to load the second binary?

**Comment by Lorenzooone** [comment]
It really shouldn't lead to PIC code. You'd be basically replacing the loader binary with your main binary itself. So it should work fine. Though you may need to make a linker file yourself for it to work.

For loading, I am just proposing a way to do it. I've never had to implemented it myself.
What I'd do is copy the loading binary to a safe space (VRAM or shared WRAM http://problemkaputt.de/gbatek-ds-memory-maps.htm ) and then execute it to load the actual binary to the Main RAM using something to load from "cartridge" (again, never done this).
Once the loading is done, I'd jump to the initial execution address of your code.

**Comment by ds-sloth** [comment]
If this could be pulled off, it has an additional advantage that the stage 1 loader could safely check whether it's running on a DSi and complain if not. But frankly I'm not familiar enough with linker scripts or the DS memory layout to implement it.

**Comment by WinterMute** [comment]
Please wait for us to have a look at what's going on here rather than reinventing some way to bodge up loading large binaries. We think this may be possible using overlays which appear to the application as static symbols and don't require PIC. We do kind of need more information about the project to say for sure. @ds-sloth if you don't want to reveal what this is in public then feel free to email support@devkitpro.org & we'll see what we can figure out.
